---
title: "HiSeq report"
author: "Ming Wang"
date: "`r Sys.Date()`"
output:
  html_document:
    highlight: tango
    toc: yes
    toc_float:
      collapsed: yes
    keep_md: false
  pdf_document:
    toc: yes
params:
  input_dir: ""
---

```{r setup, include=FALSE}
suppressPackageStartupMessages(library(knitr))

knitr::opts_chunk$set(fig.width  = 12, 
                      fig.height = 8, 
                      fig.path   = "Figures/",
                      eval       = TRUE,
                      echo       = FALSE,
                      cache      = FALSE,
                      prompt     = FALSE,
                      tidy       = FALSE,
                      comment    = NA,
                      message    = FALSE,
                      warning    = FALSE,
                      eval       = T,
                      rownames.print = FALSE)
```


```{r load pkg}
library(hiseqr)
library(knitr)
library(ggplot2)
library(ggthemes)
library(ggrepel)
library(fishualize)
library(patchwork)
library(dplyr)
library(tidyr)
library(glue)
```


```{r config, eval = T}
input_dir <- params$input_dir
input_dir <- normalizePath(input_dir)
if(! is_hiseq_dir(input_dir, "trim_r1")) {
  stop(paste0("Input is not trim_r1 directory: ", input_dir))
}
```


```{r loading data}
pd <- read_hiseq(input_dir)
df <- read_hiseq_trim(input_dir)

n_smp <- length(list_hiseq_file(input_dir, "smp_name", TRUE))
total <- round(sum(df$input) / 1e6, 1)
clean <- round(sum(df$output) / 1e6, 1)
clean_pct <- tryCatch(
  error = function(cnd) 0,
  round(clean / total * 100, 2)
)
```


## 1 Summary

```{r summary, results="asis"}
sum_text <- glue::glue(
  "A total of {n_smp} samples; {total}M input reads,",
  "output {clean}M ({clean_pct}%) reads"
)
print(sum_text)
```


## 2 Results

### 2.1 Table1. Number of reads

```{r}
hiseqr::to_DT(df)
```

### 2.2 Figure 1. Number of mapped reads

```{r figure1_trim_reads, fig.width=6, fig.height=3}
plot_hiseq_trim(input_dir)
```

## 3 Methods

```{r}
df_args <- data.frame(
  group = c(
    "Adapter3(read1)",
    "Adapter5(read1)",
    "Adapter3(read2)",
    "Adapter5(read2)",
    "cut_before_trim",
    "cut_after_trim",
    "cut_to_length",
    "error_rate",
    "minimum_length",
    "overlap",
    "minimum_quality",
    "remove polyN",
    "remove untrim",
    "remove dup"
  ),
  parameter = c(
    "-a", "-g", "-A", "-G", 
    "--cut-before-trim",
    "--cut-after-trim",
    "--cut-to-length",
    "-e", "-m", "-O", "-q", "--rm-polyN", "--rm-untrim", "--rmdup" 
  ),
  value = c(
    ifelse(is.null(pd$args$adapter3), "None", pd$args$adapter3),
    ifelse(is.null(pd$args$adapter5), "None", pd$args$adapter5),
    ifelse(is.null(pd$args$Adapter3), "None", pd$args$adapter5),
    ifelse(is.null(pd$args$Adapter5), "None", pd$args$adapter5),
    pd$args$cut_before_trim,
    ifelse(is.null(pd$args$cut_after_trim), "0",  pd$args$cut_after_trim),
    pd$args$cut_to_length,
    pd$args$error_rate,
    pd$args$len_min,
    pd$args$overlap,
    pd$args$qual_min,
    pd$args$rm_polyN,
    pd$args$rm_untrim,
    pd$args$rmdup
  )
)

hiseqr::to_DT(df_args)
```




**END**
