---
title: "HiSeq report"
author: "Ming Wang"
date: "`r Sys.Date()`"
output:
  html_document:
    highlight: tango
    toc: yes
    toc_float:
      collapsed: no
    keep_md: false
  word_document:
    toc: yes
  pdf_document:
    toc: yes
params:
  input_dir: ""
---

```{r setup, include=FALSE}
suppressPackageStartupMessages(library(knitr))

knitr::opts_chunk$set(fig.width  = 12, 
                      fig.height = 8, 
                      fig.path   = "Figures/",
                      eval       = TRUE,
                      echo       = FALSE,
                      cache      = FALSE,
                      prompt     = FALSE,
                      tidy       = FALSE,
                      comment    = NA,
                      message    = FALSE,
                      warning    = FALSE,
                      eval       = T,
                      rownames.print = FALSE)
```


```{r load pkg}
library(hiseqr)
library(knitr)
library(ggplot2)
library(ggthemes)
library(ggrepel)
library(fishualize)
library(patchwork)
library(dplyr)
library(tidyr)
library(glue)
```


```{r config, eval = T}
input_dir <- params$input_dir
# input_dir <- ".."
input_dir <- normalizePath(input_dir)
if(! is_hiseq_dir(input_dir, "_r1")) {
  stop(paste0("Input file is not alignment_r1 directory: ", input_dir))
}
```


```{r loading data}
pd <- read_hiseq(input_dir)
df_align <- read_hiseq_align(input_dir)

# summary
n_smp    <- 1
total    <- df_align %>% pull(total)
map      <- df_align %>% pull(map)
map_pct  <- round(map / total * 100, 2)
total <- round(total / 1e6, 2)
map   <- round(map / 1e6, 2)
```


## 1 Summary

```{r summary, results="asis"}
sum_text <- glue::glue(
  "A total of {n_smp} samples; {total}M sequencing depth ",
  "with {map}M ({map_pct}%) reads mapped to reference genome; "
)
print(sum_text)
```


## 2 Results

### 2.1 Table1. Mito Percentage

```{r}
df_align %>% 
  hiseqr::to_DT()
```

### 2.2 Figure 1. Number of mapped reads

+ Map percentage

```{r figure1_align_reads, fig.width=6, fig.height=3}
plot_hiseq_align(input_dir, columns = c("map", "unmap"))
```

+ Unique percentage

```{r figure1_unique_reads, fig.width=6, fig.height=3}
plot_hiseq_align(input_dir, columns = c("unique", "multi", "unmap"))
```

